### ISSUE TITLE
add sitemaps.xml

### ISSUE THREAD

**Issue by iabhi7** [falso-tech/falso-tech.github.io#10]
[Google's direction to use sitemaps](https://support.google.com/webmasters/answer/183668?hl=en)

**Comment by pyaf** [comment]
Added sitemap.xml file [here](https://github.com/falso-tech/falso-tech.github.io/commit/eecd25de587c68ab407ee9aef4a39e720ff43c30).

We need to setup an url for this file; https://falso.tech/sitemap.xml which should render the sitemap.xml file. (Not sure how to setup urls in Jekyll)

Also, once the url is setup, we have to add the sitemap url to [Google Console](https://search.google.com/search-console/about). [Search console dashboard > Crawl > Sitemaps]

**Comment by iabhi7** [comment]
We don't need to setup an url for the file, it will automatically redirect it to [https://falso.tech/sitemap.xml](https://falso.tech/sitemap.xml). 
Added on Google console will add on other search engines console later.
Merging the branch with master for now.
